[project]
name = "llmcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lmstudio>=1.4.1",
    "prompt-toolkit>=3.0.51",
    "pydantic>=2.11.7",
    "pyperclip>=1.9.0",
    "typer>=0.16.0",
]
